// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvv1RxU-RVn_3QEwmWb_WacQI5AG4G7u4',
    appId: '1:639510859177:web:c05423707d80d2be9bc8b8',
    messagingSenderId: '639510859177',
    projectId: 'autorizaciones-remotas-be014',
    authDomain: 'autorizaciones-remotas-be014.firebaseapp.com',
    storageBucket: 'autorizaciones-remotas-be014.appspot.com',
    measurementId: 'G-M4WBPLJD0Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZwesp99LSOzmXgJ_jzqwh1bn09a4xse4',
    appId: '1:639510859177:android:be3f003e7c4aedfe9bc8b8',
    messagingSenderId: '639510859177',
    projectId: 'autorizaciones-remotas-be014',
    storageBucket: 'autorizaciones-remotas-be014.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpGPrCksvwBO51kuz1v1UguJKAQQwh3pc',
    appId: '1:639510859177:ios:1ce7010a9d0cb43f9bc8b8',
    messagingSenderId: '639510859177',
    projectId: 'autorizaciones-remotas-be014',
    storageBucket: 'autorizaciones-remotas-be014.appspot.com',
    iosBundleId: 'com.intelaf.autorizacionesRemota',
  );
}
